nota1 = int(input("qual e sua nota  "))
nota2 = int (input("qual e sua nota "))
nota3 = int (input("qual e sua nota"))
soma = float(nota1 + nota2 + nota3)
media = float(soma /3)
print("A media desse aluno é " + str(media) + "postos? ")
nota4 = int(input("Qual e a 4º nota "))
media2 = int(media + nota4 /4)
print ("A nova media e " + str(media2))
